# Site settings
title: "Chet L Williams"
description: "My CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chet L. Williams"
resume_title:                   "Senior Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "chet@chetlwilliams.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "240-450-2920"
resume_contact_address:         "4 Crest Ct. Hickory Creek, Texas 75065"

resume_header_contact_info:     "4 Crest Ct. Hickory Creek, Texas • 240-450-2920 • chet@chetlwilliams.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am an Air Force veteran with over 20 years experience in network and datacenter building. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/clamontwilliams"
  resume_twitter_url:           "http://twitter.com/clamontwilliams"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/chetwilliams1/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://chetlwilliams.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
